name: "LiteBoard"
description: "Dashboard ligero local para Home Assistant"
slug: "liteboard"
version: "1.0.4"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/JordiMD92/LIteBoard"
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "LiteBoard web interface"
map:
  - config:rw
startup: application
panel_icon: "mdi:bulletin-board"
options: {}
schema: {}